/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hzy_exampledemo_ui_ndk_HelloWorld */

#ifndef _Included_com_hzy_exampledemo_ui_ndk_HelloWorld
#define _Included_com_hzy_exampledemo_ui_ndk_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hzy_exampledemo_ui_ndk_HelloWorld
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hzy_exampledemo_ui_ndk_HelloWorld_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
